#!/bin/bash
#
# tervitusskript
#
echo -n "Tere, Eros! " #siia kirjutasin enda skripti -n tähendab, et reavahetust ei ole
echo " " #siia jätsin tühiku ja ilma -n, sest me soovime reavahetust
#
# skripti lõpp
